### ISSUE TITLE
Oddaja kratkega poročila

### ISSUE THREAD

**Issue by mitja-mandic** [mitja-mandic/grid-peeling#1]
Pozdravljeni,
danes je rok za oddajo kratkega poročila za projekt, vendar ni navodil kam ga oddati. Ga pošljemo profesorju ali vam po mailu ali je dovolj da je na githubu?

**Comment by jaanos** [comment]
Lahko je na GitHubu, pa pošljeta povezavo prof. Cabellu.

**Comment by mitja-mandic** [comment]
Hvala za odgovor. Povezavo sem poslal profesorju.
