### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by mitja-mandic** [mitja-mandic/grid-peeling#2]
Pozdravljeni, 
z delom na projektu sva zaključila. Poročilo je v datoteki porocilo.pdf, koda je v pythonovih datotekah, vizualizacija pa v vizualizacija.ipynb jupyter notebooku (vse to je tudi omenjeno v poročilu).  Ali moram povezavo poslati še profesorju?

Zanima me še, kdaj bodo potekali zagovori? Nama s partnerjem bi najbolj ustrezalo v petek zjutraj (pred 10, potem imamo predavanja do 13), seveda pa sva prilagodljiva.

Mitja

**Comment by jaanos** [comment]
Povezavo kar pošljita še prof. Cabellu v vednost. Termine zagovorov bomo še sporočili.
